### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by ArcaneDisgea**
*goat please don't kill me for all of these hardcoded values*

I tweaked it some, next few goals are:

- PvP team under FC
- Eureka/Bozja Icons
- Extend background to top to match and give header the same rectangle opacity that matches the rest maybe?

### CODE REVIEW

**Comment by ArcaneDisgea** [comment]
Updated to remove mettle and swap bozja/eureka positions.

always shows bozja levels now, it would disappear if the user didnt have a level yet no wit just shows 0 like eureka, thanks for the consistency SE

adjusted mimo percent to be 0 if user has none based on feedback from a user

**Comment by ArcaneDisgea** [comment]
Aight this can prolly be glanced over and merged after ridiculing me for shitting all over goats nice refactor he did. *Sorry goat*

**Comment by karashiiro** [comment]
Should do something about the job icons at some point, maybe store them in an object and just run a loop or something to reduce that massive block of repetitive code. Can do that later though, lgtm.

**Comment by ArcaneDisgea** [comment]
> Should do something about the job icons at some point, maybe store them in an object and just run a loop or something to reduce that massive block of repetitive code. Can do that later though, lgtm.

Think storing it in an array and iterating through it in waves would work? For example do all job images in one wave and then all job levels in one wave?

**Comment by karashiiro** [comment]
I'd make an array with an object like
```
{
  classJobId: number;
  classJobImage: string;
  pos: {
    x: number;
    y: number;
  };
}
```
and then iterate over that, doing both the images and the levels at once, but how workable that is depends on if the classjob images are constant or not. Pseudocode would be like
```js
for (const classJobInfo of lodestoneReturnedInfo) {
  const canvasingInfo = CJ_CANVASING_INFO.find(c => c.classJobId === classJobInfo.ID);
  drawImage(canvasingInfo.classJobImage, canvasingInfo.pos.x, canvasingInfo.pos.y);
  drawText("" + classJobInfo.Level, canvasingInfo.pos.x + WIDTH_OF_ICON, canvasingInfo.pos.y);
}
```

**Comment by karashiiro** [comment]
You might need another array or object keeping track of the specific positions where each icon+level is supposed to go, but that's the gist of it. It'd be a fairly large refactor, so it can be set aside for now, probably.

**Comment by karashiiro** [comment]
And would need some special-casing as well for some jobs, but that should be minimal and just be done inside the loop.

**Comment by karashiiro** [comment]
Or, even better, have a CanvasGrid class that takes an array of the elements that corresponds to their relative positions on that grid in its constructor, and just do all of the actual calculations inside of that class, doing significantly less manual positioning overall.

**Pull request merged**
